{{ if has "prometheus" .Values.pump.backend }}
{{ if .Values.pump.prometheusPump.prometheusOperator.enabled }}
apiVersion: {{ .Values.pump.prometheusPump.prometheusOperator.apiVersion }}
kind: {{ .Values.pump.prometheusPump.prometheusOperator.kind }}
metadata:
  name: tyk-pump-podmonitor-{{ include "tyk-pump.fullname" . }}
  labels:
    {{- range $key, $value := .Values.pump.prometheusPump.prometheusOperator.podMonitorSelector }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: pump-{{ include "tyk-pump.fullname" . }}
  endpoints:
    - port: tyk-pump-port
      interval: "30s"
  podMetricsEndpoints:
    - port: tyk-pump-port
{{ end }}
{{ end }}
